### ISSUE TITLE
systctl-33 - undefined method `expect'

### ISSUE THREAD

**Issue by kskrisss** [dev-sec/linux-baseline#107]
**Describe the bug**

After updating inspect from 3.0.25 to 3.0.42 we have started to see an issue with undefined method `expect' and tests fail

**Expected behavior**
the test should finish successfully 

**Actual behavior**

```
sudo inspec exec https://github.com/dev-sec/linux-baseline

    amazon-ebs:   ✔  sysctl-32: kernel.randomize_va_space
    amazon-ebs:      ✔  Kernel Parameter kernel.randomize_va_space value should eq 2
    amazon-ebs:   ×  sysctl-33: CPU No execution Flag or Kernel ExecShield
    amazon-ebs:      ×  /proc/cpuinfo Flags should include NX
    amazon-ebs:      undefined method `expect' for #<RSpec::ExampleGroups::ProcCpuinfo:0x0000000002d70508>
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: Profile Summary: 52 successful controls, 1 control failure, 1 control skipped
    amazon-ebs: Test Summary: 124 successful, 1 failure, 1 skipped
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-0971ba41c98f72259)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1

grep nx /proc/cpuinfo
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 ida arat pku ospke



```
**OS / Environment**
```
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```
**Inspec Version**
```
3.0.25 - finishes with success
3.0.42 - fails

```

**Baseline Version**
```
latest 
https://github.com/dev-sec/linux-baseline/commit/149a2589ab08a135461986c878205669d4df2f33

```

**Additional context**
building AWS machine image with packer and testing it with inspect

```
SUCCES
	{
	    "type": "shell",
	    "inline": ["sudo sh inspec/install.sh -v 3.0.25 -P inspec"]
	},
	{
	    "type": "shell",
	    "inline": ["sudo inspec exec https://github.com/dev-sec/linux-baseline"]
	},

FAILURE
	{
	    "type": "shell",
	    "inline": ["sudo sh inspec/install.sh -P inspec"]
	},
	{
	    "type": "shell",
	    "inline": ["sudo inspec exec https://github.com/dev-sec/linux-baseline"]
	},
```

**Comment by artem-sidorenko** [comment]
@kskrisss thanks for reporting this!

@chris-rock are you aware of any changes related to this issue in the last inspec versions?

**Comment by shoekstra** [comment]
Same exists in 3.0.52.

**Comment by artem-sidorenko** [comment]
@kskrisss @shoekstra is this issue still there? Any idea how to reproduce it (maybe even without AWS)?

**Comment by chris-rock** [comment]
Should we open an issue in InSpec? From the description, it seems to be a bug there?

**Comment by artem-sidorenko** [comment]
@chris-rock for me - it works, I could not reproduce it with test-kitchen of chef-os-hardening and latest gems (inspec 3.7.1). So it makes sense to know first if this problem is still there and can be reproduced

**Comment by kskrisss** [comment]
could not reproduce any more, Issue is resolved now. Closing
